FROM python:3.7-slim

WORKDIR /app

COPY ./requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

COPY ./mysite .

# Disables output buffering, so the output from your Python application is printed to the console in real-time.
ENV PYTHONUNBUFFERED=1